### PR TITLE
Few changes

### PR DESCRIPTION
**Pull request by tobyf93**

### CODE REVIEW

**Comment by ga-wolf** [comment]
Does that all make sense now? I can try explaining it again if that helps?

**Comment by tobyf93** [comment]
Nah i think i've got my head around it.  Just getting used to the differences between git and mercurial.

**Comment by ga-wolf** [comment]
Perfect

**Comment by tobyf93** [comment]
So would it be common practise to have two upstreams - one for development and one for production?  I'm guessing remote names are free to be named whatever e.g. development instead of upstream?

**Comment by ga-wolf** [comment]
Nope, that's where branches come in to play.  You normally would have feature branches - so a branch based on what you are currently working on. The master branch should always be ready to push to production.

An "upstream" can only be a Github repository that you have forked from (except a very few cases that you don't need to worry about just yet).  And it always needs to be called upstream

**Comment by tobyf93** [comment]
Ok so you'd have multiple branches - say master and develop.  Does that mean it would be the Project Managers role to pull the upstream and merge branches when code is ready to be released?

**Comment by ga-wolf** [comment]
Each individual has to pull the upstream down to his local computer - that isn't something that is automated.  Normally it is the lead dev who merges the branches

**Pull request merged**
