### PR TITLE
Week 1

### PR DESCRIPTION
**Pull request by tobyf93**
> > How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible
> > 0 - only really thing i had to lookup was regex functions/syntax.
> > 
> > Was there anything that you struggled with?
> > No
> > 
> > Is there anything that you'd like some further information on?
> > I think it would be useful covering regular expression syntax.  Never really covered it formally, always just winged it when needed.
> > 
> > Roughly, how long did it take?
> > Hour and a half.

### CODE REVIEW

**Comment by ga-wolf** [comment]
Perfect mate. Looks great - code looks really nice. We will be doing a whole topic of RegExp but a little later on in the course - still a bit too early for most people!  http://regexone.com/ probably isn't a horrible place to start though

**Comment by ga-wolf** [comment]
Well done

**Comment by tobyf93** [comment]
Thanks for the feedback :)

**Comment by ga-wolf** [comment]
No problems at all!

**Pull request merged**
