### PR TITLE
Added 3 homeworks

### PR DESCRIPTION
**Pull request by one19**
I've added the three previous homeworks. I will fix several problems with the website generation HW1 this weekend, and am working on making the cat-gif page something much more dynamic. I'd say these homeworks were 7/10 difficulty because they take such a large amount of time, and design effort. HTML & CSS are definitely one of my weak-points, and I haven't had as much time as I've wanted this week to work on getting better.

I'm still working through the documentation for HTML and CSS code, but if you know of any good design-method or good design docs for web pages, I'd devour that. I'm so far behind the times on what's good and what's shit that it's laughable.

I've only been able to spend about 2 hours on each homework. This will change tomorrow and in the future (life-shit will thankfully die down).

### CODE REVIEW

**Comment by ga-wolf** [comment]
Perfect mate! Let me know when you have done whatever is planned with the cat thing!  You did a good job on everything that I saw...

Don't know of any design methods... Most people just copy haha. Here are a couple of places that are good to check out
- http://www.awwwards.com/
- http://wow-web.co.uk/
- https://onepagelove.com/

Cool to hear that you are going to start getting more time!

**Comment by ga-wolf** [comment]
Have a chat with me about the design stuff though - I could end up having a few resources - just not quite sure what you are asking for haha.

**Comment by one19** [comment]
Sweet! I'll kinda take a look tonight and tomorrow, and get a better idea
about what I'm asking for design principles. But those links look
excellent, thanks!

**Comment by ga-wolf** [comment]
No problems mate!

**Pull request merged**
