### PR TITLE
Homework Week 1

### PR DESCRIPTION
**Pull request by aaronongtw**
2

Knowing whats the best code for the situation

2 hours

### CODE REVIEW

**Comment by ga-wolf** [comment]
Perfect mate. Looks great!

In the notBad function - it is worth checking out whether the indexOf bad comes after the indexOf not in the if statement as well.

**Comment by aaronongtw** [comment]
made the adjustments, would i need to lodge another pull request?

**Comment by ga-wolf** [comment]
Nope all good - they'll come through on the next pull request anyway

**Comment by ga-wolf** [comment]
Thanks for making the changes though

**Comment by aaronongtw** [comment]
Thanks

**Comment by ga-wolf** [comment]
No problems!

**Pull request merged**
